cmake_minimum_required(VERSION 2.8)
project(Calibrate)

set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_SOURCE_DIR}/cmake")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
SET (CMAKE_CXX_COMPILER "/usr/bin/g++")

find_package(ROOT REQUIRED)
find_package(AUSALIB REQUIRED)
link_libraries(AUSA::AUSA ROOT::Core ROOT::ROOTDataFrame ROOT::Physics)

add_executable(sim_compare sim_compare.cpp)
add_executable(Dalitz_3D Dalitz_3D.cpp)
add_executable(tdc_plot tdc_plot.cpp)
add_executable(depend_mul depend_mul.cpp)
add_executable(depend_E depend_E.cpp)
add_executable(width_converter width_converter.cpp)
add_executable(depend_width depend_width.cpp)
add_executable(ang_compare ang_compare.cpp)
add_executable(ang_compare_single ang_compare_single.cpp)
add_executable(theta theta.cpp)
add_executable(ang_cor_fit ang_cor_fit.cpp)
add_executable(corr_funcs corr_funcs.cpp)
add_executable(momentum_analysis momentum_analysis.cpp)
add_executable(multiple_components multiple_components.cpp)
add_executable(cuts cuts.cpp)
add_executable(dalitz_fitter dalitz_fitter.cpp)
add_executable(phase_space phase_space.cpp)
